export const caseStudiesSeo = {
  title: 'UGC Case Studies & High-Converting Video Portfolio',
  description:
    'Browse our video creative portfolio and case studies showing high CTR, engagement rates, and ROI gains from real DTC brands using our vetted creators.',
  keywords:
    'UGC case studies, direct response video portfolio, DTC ad CTR, TikTok ad ROI, Facebook ad creatives, performance marketing cases',
  schema: {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    name: 'UGC-Direct Case Studies & Creative Lab',
    description:
      'A collection of conversion-focused video advertisements and performance analytics generated by our vetted creators.',
    url: 'https://ugc-direct.com/case-studies',
  },
};
